apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: greenpulse
resources:
  - namespace.yaml
  - deployment-ingestion-api.yaml
  - deployment-sensor-emulator.yaml
  - deployment-dashboard.yaml
  - hpa-ingestion-api.yaml
# Apply Secret separately: kubectl apply -f secret.example.yaml (after envsubst) or kubectl create secret ...
